DROP TABLE IF EXISTS account;

CREATE TABLE account(
	id INT NOT NULL AUTO_INCREMENT,
	hashedpass VARCHAR(255) NOT NULL,
	username VARCHAR(255) NOT NULL,
	firstName VARCHAR(255) NOT NULL,
	lastName VARCHAR(255) NOT NULL,
	email VARCHAR(255) NOT NULL,
	birthday VARCHAR(255) NOT NULL,
	friends VARCHAR(255) NOT NULL,
	PRIMARY KEY (ID)
);